### ISSUE TITLE
Ignore unsupported myst tokens in myst -> schema conversion

### ISSUE THREAD

**Issue by fwkoch** [curvenote/schema#59] opened 2022-04-26 19:33 UTC
This fails in the chrome extension:

![image](https://user-images.githubusercontent.com/9453731/165378040-3dada810-ab13-4885-866e-4d5738b71423.png)

For now, we can just ignore this html type.

**Comment by rowanc1** [comment] 2022-04-27 00:25
Duplicate of #58

**Closed** 2022-04-27 00:26 UTC
Labels: bug
